version: '3.8'

services:
  # MongoDB service
  mongodb_service:
    image: mongo
    container_name: mongodb_service
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  # Go application service
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: go_app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - APP_PORT=${APP_PORT}
    depends_on:
      - mongodb_service
    volumes:
      - ./api:/app

volumes:
  mongo_data:
